name: 'Install Dependencies'
description: 'Install Node.js dependencies'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Cache yarn packages to speed up installation
    - name: Cache Yarn packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # Install dependencies
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
