name: 'Setup EAS'
description: 'Set up EAS and install dependencies'

inputs:
  expo-token:
    description: 'Expo token for authentication'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20.x'

runs:
  using: 'composite'
  steps:
    - name: Check for EXPO_TOKEN
      run: |
        if [ -z "${{ inputs.expo-token }}" ]; then
          echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
          exit 1
        fi
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.expo-token }}

    - name: Install dependencies
      run: yarn install
      shell: bash