name: 'Setup JS Runtime Environment'
description: 'Sets up Node.js and caches Node modules'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'yarn'

    - name: Cache Yarn packages
      uses: actions/cache@v2
      with:
        path: ~/.yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
