name: android-preview-build-local
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  update:
    name: EAS Android Build Local
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup environment variables
        run: |
          echo "MAPBOX_DOWNLOADS_TOKEN=$MAPBOX_DOWNLOADS_TOKEN" >> $GITHUB_ENV

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Prebuild
        run: |
          echo "Using Mapbox Token: $MAPBOX_DOWNLOADS_TOKEN"
          export MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          yarn run prebuild:expo

      - name: Create preview
        run: |
          echo "Using Mapbox Token: $MAPBOX_DOWNLOADS_TOKEN"
          export MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          eas build --platform android --profile preview --local
          echo "apk_path=$(find apps/expo -name '*.apk')" >> $GITHUB_OUTPUT
        working-directory: apps/expo
        env:
          DEBUG: "true"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: ${{ steps.build.outputs.apk_path }}

      - name: Create Commit Comment
        if: github.event_name == 'push'
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Android APK build completed!
            You can download the APK file from the following link:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts

# <<<<<<< feat/upgrade-expo-50

#       - name: Set Environment Tokens
#         run: export MAPBOX_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

#       - name: Create preview
#         run: |
#           eas build --platform android --profile preview --local

#       - name: Build APK for Preview
#         uses: expo/expo-github-action/preview@v8
#         continue-on-error: true
#         with:
#           working-directory: apps/expo
#           command: |
#             eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk

#       - name: Upload APK artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: app-release
#           path: ${{ github.workspace }}/app-release.apk




#       # - name: Set Environment Tokens
#       #   uses: ./.github/actions/set-env-tokens
#       #   continue-on-error: true
#       #   with:
#           # mapbox_token: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
# =======

