name: android-build-apk

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: ./.github/actions/install-deps
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Prebuild
        run: |
          echo "Using Mapbox Token: $MAPBOX_DOWNLOADS_TOKEN"
          export MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          yarn run prebuild:expo

      - name: Build Android Release
        run: |
          cd apps/expo/android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
